[project]
name = "ollama-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.2",
    "pydantic>=2.11.7",
]
